name = "Skeleton Theme"
store = "surf-turf-2-0.myshopify.com"

[environments.production]
theme = "141470990497"

[environments.staging]
theme = "141473448097"

[environments.develop]
theme = "141473513633"
password = "shptka_294aec36b0fc33c2f1779ec474752d08"
