name = "Skeleton Theme"
store = "surf-turf-2-0.myshopify.com"

[environments.production]
theme_id = "141470990497"

[environments.staging]
theme_id = "141473448097"

[environments.develop]
theme = "141473513633"
